### ISSUE TITLE
Fallback

### ISSUE THREAD

**Issue by sindresorhus** [kevva/ink-image#1]
Only iTerm supports this, so would be useful with a fallback.

Maybe something like:

```jsx
render((
	<div>
		<Image preserveAspectRatio src='unicorn.jpg' width='50%'>
			Fallback text.
		</Image>
	</div>
));
```

Could also probably add a method to [`term-img`](https://github.com/sindresorhus/term-img) to return the string instead of logging directly, so you could use that module here and get the fallback logic for free.

**Comment by sindresorhus** [comment]
Or maybe better to follow `<img>` and do:

```jsx
render((
	<div>
		<Image preserveAspectRatio src='unicorn.jpg' width='50%' alt="Fallback text."/>
	</div>
));
```

**Comment by kevva** [comment]
Good idea. Will add when https://github.com/sindresorhus/term-img/pull/3 is merged.

**Comment by sindresorhus** [comment]
Done
